{
 "title": "Prometheus-PushGateway-Example",
 "time": { "from": "2021-09-09T13:27:24.272Z", "to": "2021-09-09T13:50:52.390Z" },
 "templating": {
  "list": [
   { "name": "AdhocFilters", "label": "Filters" }
  ]
 },
 "panels": [
  {
   "title": "Current CPU Usage",
   "type": "gauge",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    { "expr": "sum(cpu_usage)" }
   ]
  },
  {
   "title": "Average CPU Usage",
   "type": "gauge",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    { "expr": "avg(cpu_usage)" }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    { "expr": "topk(10,cpu_usage)", "legendFormat": "{{process}} {{pid}}" }
   ]
  },
  {
   "title": "Historical CPU Usage",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "topk(10,cpu_usage)", "legendFormat": "{{process}} {{pid}}" }
   ]
  }
 ]
}